export const mockEvents = [
  {
    title: 'Tech Career Fair 2026',
    organizer: 'TechConnect',
    date: 'January 15, 2026',
    time: '10:00 AM - 4:00 PM',
    location: 'San Francisco Convention Center',
    attendees: 250,
    description: 'Meet with top tech companies hiring for engineering, design, and product roles. Network with industry professionals and learn about exciting opportunities.',
    tags: [
      { label: 'Career Fair', variant: 'purple' },
      { label: 'In-Person', variant: 'green' },
      { label: 'Tech', variant: 'blue' },
    ],
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
  },
  {
    title: 'UX Design Workshop',
    organizer: 'Design Masters Inc',
    date: 'January 20, 2026',
    time: '2:00 PM - 5:00 PM',
    location: 'Virtual Event',
    attendees: 180,
    description: 'Learn advanced UX design techniques from industry experts. Hands-on workshop covering user research, wireframing, prototyping, and user testing.',
    tags: [
      { label: 'Workshop', variant: 'pink' },
      { label: 'Virtual', variant: 'orange' },
      { label: 'Design', variant: 'teal' },
    ],
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
  },
  {
    title: 'Startup Networking Mixer',
    organizer: 'StartupHub',
    date: 'January 25, 2026',
    time: '6:00 PM - 9:00 PM',
    location: 'Downtown Tech Hub',
    attendees: 120,
    description: 'Connect with startup founders, investors, and fellow entrepreneurs. Great opportunity to expand your network and discover new opportunities in the startup ecosystem.',
    tags: [
      { label: 'Networking', variant: 'purple' },
      { label: 'In-Person', variant: 'green' },
      { label: 'Startup', variant: 'blue' },
    ],
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80',
  },
  {
    title: 'Data Science Summit',
    organizer: 'DataPro Association',
    date: 'February 1, 2026',
    time: '9:00 AM - 6:00 PM',
    location: 'Boston Convention Center',
    attendees: 400,
    description: 'Full-day conference featuring talks from leading data scientists, hands-on workshops, and networking sessions. Learn about the latest trends in ML, AI, and data analytics.',
    tags: [
      { label: 'Conference', variant: 'pink' },
      { label: 'In-Person', variant: 'green' },
      { label: 'Data Science', variant: 'purple' },
    ],
    image: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800&q=80',
  },
  {
    title: 'Product Management Bootcamp',
    organizer: 'PM Academy',
    date: 'February 5, 2026',
    time: '1:00 PM - 4:00 PM',
    location: 'Virtual Event',
    attendees: 200,
    description: 'Intensive bootcamp covering product strategy, roadmapping, stakeholder management, and metrics. Perfect for aspiring and current product managers.',
    tags: [
      { label: 'Bootcamp', variant: 'orange' },
      { label: 'Virtual', variant: 'orange' },
      { label: 'Product', variant: 'teal' },
    ],
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
  },
  {
    title: 'Women in Tech Panel',
    organizer: 'WomenTech Global',
    date: 'February 10, 2026',
    time: '7:00 PM - 9:00 PM',
    location: 'Tech Campus Auditorium',
    attendees: 150,
    description: 'Inspiring panel discussion with successful women leaders in technology. Hear their stories, challenges, and advice for breaking into and advancing in tech careers.',
    tags: [
      { label: 'Panel', variant: 'pink' },
      { label: 'In-Person', variant: 'green' },
      { label: 'Diversity', variant: 'blue' },
    ],
    image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80',
  },
];
