export const mockResources = [
  {
    title: 'Professional Resume Template',
    description: 'Modern, ATS-friendly resume template that helps you stand out. Includes multiple layouts and customization options.',
    category: 'Resume',
    categoryVariant: 'purple',
    fileSize: '2.5 MB',
    fileType: 'PDF',
    downloads: 1240,
    iconType: 'FileText',
  },
  {
    title: 'Interview Preparation Guide',
    description: 'Comprehensive guide covering common interview questions, behavioral questions, and expert tips for success.',
    category: 'Interview',
    categoryVariant: 'green',
    fileSize: '4.2 MB',
    fileType: 'PDF',
    downloads: 2156,
    iconType: 'BookOpen',
  },
  {
    title: 'Cover Letter Templates',
    description: 'Collection of professional cover letter templates for various industries and experience levels.',
    category: 'Cover Letter',
    categoryVariant: 'orange',
    fileSize: '1.8 MB',
    fileType: 'DOCX',
    downloads: 945,
    iconType: 'File',
  },
  {
    title: 'Salary Negotiation Toolkit',
    description: 'Learn how to effectively negotiate your salary with proven strategies and real-world examples.',
    category: 'Career Tips',
    categoryVariant: 'pink',
    fileSize: '3.1 MB',
    fileType: 'PDF',
    downloads: 1567,
    iconType: 'FileText',
  },
  {
    title: 'LinkedIn Profile Optimization',
    description: 'Step-by-step guide to creating a compelling LinkedIn profile that attracts recruiters and opportunities.',
    category: 'LinkedIn',
    categoryVariant: 'blue',
    fileSize: '5.4 MB',
    fileType: 'PDF',
    downloads: 3421,
    iconType: 'BookOpen',
  },
  {
    title: 'Portfolio Building Guide',
    description: 'Create a stunning portfolio that showcases your work effectively. Includes examples and best practices.',
    category: 'Portfolio',
    categoryVariant: 'teal',
    fileSize: '6.8 MB',
    fileType: 'PDF',
    downloads: 892,
    iconType: 'FileText',
  },
  {
    title: 'Technical Interview Prep',
    description: 'Master technical interviews with coding challenges, system design questions, and data structure guides.',
    category: 'Interview',
    categoryVariant: 'purple',
    fileSize: '8.2 MB',
    fileType: 'PDF',
    downloads: 2845,
    iconType: 'BookOpen',
  },
  {
    title: 'Career Transition Roadmap',
    description: 'Strategic guide for successfully transitioning to a new career path. Includes action plans and timelines.',
    category: 'Career Tips',
    categoryVariant: 'pink',
    fileSize: '3.7 MB',
    fileType: 'PDF',
    downloads: 1234,
    iconType: 'FileText',
  },
  {
    title: 'Remote Work Best Practices',
    description: 'Essential tips and tools for excelling in remote work environments. Stay productive and connected.',
    category: 'Remote Work',
    categoryVariant: 'green',
    fileSize: '2.9 MB',
    fileType: 'PDF',
    downloads: 1876,
    iconType: 'BookOpen',
  },
];
