export const mockResources = [
  {
    id: 1,
    title: 'Professional Resume Template',
    description: 'Modern, ATS-friendly resume template that helps you stand out. Includes multiple layouts and customization options.',
    detailedDescription: 'This comprehensive resume template package includes 5 different modern layouts designed to pass Applicant Tracking Systems (ATS) while maintaining visual appeal. Each template is fully customizable and comes with detailed instructions on how to tailor it to your specific industry and experience level. Perfect for job seekers at any stage of their career.',
    category: 'Resume',
    categoryVariant: 'purple',
    fileSize: '2.5 MB',
    fileType: 'PDF',
    downloads: 1240,
    iconType: 'FileText',
    uploadedBy: 'Career Services Team',
    uploadedDate: '2025-01-05',
    lastUpdated: '2025-01-15',
  },
  {
    id: 2,
    title: 'Interview Preparation Guide',
    description: 'Comprehensive guide covering common interview questions, behavioral questions, and expert tips for success.',
    detailedDescription: 'A complete interview preparation resource covering everything from researching companies to following up after interviews. Includes 100+ common interview questions with model answers, tips for handling behavioral questions using the STAR method, and strategies for different interview formats including phone, video, and panel interviews.',
    category: 'Interview',
    categoryVariant: 'green',
    fileSize: '4.2 MB',
    fileType: 'PDF',
    downloads: 2156,
    iconType: 'BookOpen',
    uploadedBy: 'FOP Admin',
    uploadedDate: '2025-01-08',
    lastUpdated: '2025-01-12',
  },
  {
    id: 3,
    title: 'Cover Letter Templates',
    description: 'Collection of professional cover letter templates for various industries and experience levels.',
    detailedDescription: 'Access 10 professionally crafted cover letter templates suitable for different industries including tech, finance, healthcare, and creative fields. Each template includes guidance on personalization, tone, and structure. Available in both PDF and editable DOCX formats.',
    category: 'Cover Letter',
    categoryVariant: 'orange',
    fileSize: '1.8 MB',
    fileType: 'DOCX',
    downloads: 945,
    iconType: 'File',
    uploadedBy: 'Career Services Team',
    uploadedDate: '2025-01-03',
    lastUpdated: '2025-01-10',
  },
  {
    id: 4,
    title: 'Salary Negotiation Toolkit',
    description: 'Learn how to effectively negotiate your salary with proven strategies and real-world examples.',
    detailedDescription: 'Master the art of salary negotiation with this comprehensive toolkit. Includes research strategies for determining your market value, scripts for different negotiation scenarios, tips for negotiating benefits beyond salary, and real-world case studies. Learn when and how to negotiate to maximize your compensation package.',
    category: 'Career Tips',
    categoryVariant: 'pink',
    fileSize: '3.1 MB',
    fileType: 'PDF',
    downloads: 1567,
    iconType: 'FileText',
    uploadedBy: 'FOP Admin',
    uploadedDate: '2025-01-07',
    lastUpdated: '2025-01-14',
  },
  {
    id: 5,
    title: 'LinkedIn Profile Optimization',
    description: 'Step-by-step guide to creating a compelling LinkedIn profile that attracts recruiters and opportunities.',
    detailedDescription: 'Transform your LinkedIn profile into a powerful career tool. This guide covers optimizing every section of your profile including headline, summary, experience, and skills. Learn how to use keywords effectively, build your network strategically, and leverage LinkedIn features like recommendations and endorsements to increase your visibility to recruiters.',
    category: 'LinkedIn',
    categoryVariant: 'blue',
    fileSize: '5.4 MB',
    fileType: 'PDF',
    downloads: 3421,
    iconType: 'BookOpen',
    uploadedBy: 'Tech Society',
    uploadedDate: '2025-01-02',
    lastUpdated: '2025-01-11',
  },
  {
    id: 6,
    title: 'Portfolio Building Guide',
    description: 'Create a stunning portfolio that showcases your work effectively. Includes examples and best practices.',
    detailedDescription: 'Whether you\'re a designer, developer, writer, or creative professional, this guide will help you build a portfolio that stands out. Includes tips on selecting your best work, presenting projects effectively, choosing the right platform, and creating compelling case studies. Features 20+ portfolio examples from successful professionals.',
    category: 'Portfolio',
    categoryVariant: 'teal',
    fileSize: '6.8 MB',
    fileType: 'PDF',
    downloads: 892,
    iconType: 'FileText',
    uploadedBy: 'Design Society',
    uploadedDate: '2025-01-06',
    lastUpdated: '2025-01-13',
  },
  {
    id: 7,
    title: 'Technical Interview Prep',
    description: 'Master technical interviews with coding challenges, system design questions, and data structure guides.',
    detailedDescription: 'Comprehensive technical interview preparation for software engineering roles. Covers data structures and algorithms, system design fundamentals, coding best practices, and problem-solving strategies. Includes 50+ practice problems with detailed solutions, tips for whiteboard coding, and guidance on communicating your thought process effectively.',
    category: 'Interview',
    categoryVariant: 'purple',
    fileSize: '8.2 MB',
    fileType: 'PDF',
    downloads: 2845,
    iconType: 'BookOpen',
    uploadedBy: 'Tech Society',
    uploadedDate: '2025-01-04',
    lastUpdated: '2025-01-09',
  },
  {
    id: 8,
    title: 'Career Transition Roadmap',
    description: 'Strategic guide for successfully transitioning to a new career path. Includes action plans and timelines.',
    detailedDescription: 'Making a career change? This roadmap guides you through every step of the transition process. Learn how to identify transferable skills, research new industries, build relevant experience, and position yourself as a strong candidate despite changing fields. Includes customizable action plans and realistic timelines for different types of career transitions.',
    category: 'Career Tips',
    categoryVariant: 'pink',
    fileSize: '3.7 MB',
    fileType: 'PDF',
    downloads: 1234,
    iconType: 'FileText',
    uploadedBy: 'Career Services Team',
    uploadedDate: '2025-01-01',
    lastUpdated: '2025-01-08',
  },
  {
    id: 9,
    title: 'Remote Work Best Practices',
    description: 'Essential tips and tools for excelling in remote work environments. Stay productive and connected.',
    detailedDescription: 'Thrive in remote work with this comprehensive guide covering productivity strategies, communication best practices, work-life balance tips, and essential tools for remote collaboration. Learn how to set up an effective home office, manage your time, stay connected with your team, and advance your career while working remotely.',
    category: 'Remote Work',
    categoryVariant: 'green',
    fileSize: '2.9 MB',
    fileType: 'PDF',
    downloads: 1876,
    iconType: 'BookOpen',
    uploadedBy: 'FOP Admin',
    uploadedDate: '2025-01-09',
    lastUpdated: '2025-01-16',
  },
];
